### ISSUE TITLE
The short-range/long-range mlp seem like sampling the four direction in different channel features.  

### ISSUE THREAD

**Issue by lixcli** [Sense-GVT/BCDNet#1]
Hi,
I think that some logic of the code perhaps not match the paper's method.
As the paper's state, the sampling step use a way similar to[1], which mean it will increase the channel numbers by 4 times for short-range branch and long-range branch in the mlp part, if we sample the four direction element in the sample feature. However, The mlp layer's input dimension is equal to the output dimension( both 1024, [code link](https://github.com/Sense-GVT/BCDNet/blob/594ef1b1b6bfa542882f2ea3a4f499b843d5f463/prototype/model/a_3.py#L197)). 
It means that it sample the four direction in different channel features.  

Thank's for your work and your code-sharing!:)

ref:
[1]Shift: A zero flop, zero parameter alternative to spatial convolutions.

**Comment by Xingrun-Xing** [comment]
Please refer to line [69](https://github.com/Sense-GVT/BCDNet/blob/594ef1b1b6bfa542882f2ea3a4f499b843d5f463/prototype/model/a_3.py#L69) and[ 94 ](https://github.com/Sense-GVT/BCDNet/blob/594ef1b1b6bfa542882f2ea3a4f499b843d5f463/prototype/model/a_3.py#L94)in the code, we sample 1/4 channels from each direction. So that, the input and output channels are the same.
